eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://peer1:8801/eureka
  instance:
    hostname: peer1
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/alive768/datatech-config
          searchPaths: springcloud-config
          username: xushifu@live.cn
          password: 198568xz
      label: master
  application:
    name: config-server