spring:
  application:
    name: eureka-datatech
server:
  port: 8803
eureka:
  instance:
    prefer-ip-address: true
    hostname: peer3
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8801/eureka/,http://peer2:8802/eureka/