spring:
  application:
    name: eureka-datatech
server:
  port: 8801
eureka:
  instance:
    prefer-ip-address: true
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer2:8802/eureka/,http://peer3:8803/eureka/

