spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      uri: http://peer1:8888
      profile: dev
server:
  port: 8882
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://peer1:8801/eureka
  instance:
    hostname: peer1