spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      uri: http://peer1:8888
      profile: dev
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8801/eureka/
  instance:
    hostname: peer1